name: "Create Pull Request Alert"
author: "Your Name"
description: "Create a pull request alert based on inputs"
branding:
  color: green
  icon: git-pull-request
inputs:
  repository:
    description: "Target repository for creating the pull request"
    required: true
  base-branch:
    description: "Base branch to create pull request against (e.g., main)"
    required: true
  head-branch:
    description: "Branch from which the pull request will be created"
    required: true
  pr-title:
    description: "Title of the pull request"
    required: true
  pr-body:
    description: "Body content of the pull request"
    required: false
    default: "This is an automated pull request"
  github-token:
    description: "GitHub Personal Access Token for authentication"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Create Pull Request
      env:
        GITHUB_TOKEN: ${{ inputs.secret }}  # Directly setting the token in the environment
      run: |
        gh pr create \
          --repo ${{ inputs.repository }} \
          --base ${{ inputs.base-branch }} \
          --head ${{ inputs.head-branch }} \
          --title "${{ inputs.pr-title }}" \
          --body "${{ inputs.pr-body }}"
      shell: bash
