name: "Auto Create Pull Request on Main Branch Push"
on:
  push:
    branches:
      - main

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up GitHub CLI to create the pull request
      - name: Setup GitHub CLI
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      # Create a new branch (auto-pr-branch)
      - name: Create New Branch for Pull Request
        run: |
          git checkout -b auto-pr-branch
          # Make some changes if needed
          git commit --allow-empty -m "Prepare new changes for PR"
          git push origin auto-pr-branch

      # Authorize with GitHub using a personal access token (PAT) from secret
      - name: Authorize with GitHub
        env:
          GITHUB_TOKEN: ${{ inputs.secret }}  # Using the custom PAT secret input here
        run: |
          echo "${{ inputs.secret }}" | gh auth login --with-token

      # Create a pull request from the new branch to the main branch
      - name: Create Pull Request
        run: |
          gh pr create --title "Auto PR from main branch merge" \
                       --body "This is an automatically created pull request for merging recent changes." \
                       --base main \
                       --head auto-pr-branch
