name: 'Pull Request Action'
description: 'Automatically create a pull request on branch push and notify Slack'
inputs:
  token:
    description: 'GitHub token for creating the pull request'
    required: true
  repository:
    description: 'The GitHub repository to work with'
    required: true
  base:
    description: 'The base branch to target for the pull request'
    required: true
  head:
    description: 'The head branch for the pull request'
    required: true
  slack_webhook_url:
    description: 'Slack webhook URL to send PR notifications'
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    SLACK_WEBHOOK_URL: ${{ inputs.slack_webhook_url }}
  args:
    - ${{ inputs.token }}
    - ${{ inputs.repository }}
    - ${{ inputs.base }}
    - ${{ inputs.head }}
    - ${{ inputs.slack_webhook_url }}

branding:
  icon: 'git-pull-request'
  color: 'green'
