name: "Pull Request Action"
description: "Create a pull request and send a Slack notification."
inputs:
  GITHUB_TOKEN:
    description: "GitHub Token for authentication."
    required: true
  PULL_REQUEST_HEAD:
    description: "The branch name of the head repository."
    required: true
  PULL_REQUEST_TITLE:
    description: "Title of the pull request."
    required: false
    default: "Automated Pull Request"
  PULL_REQUEST_BODY:
    description: "Body of the pull request."
    required: false
    default: "Please review the changes."
  SLACK_WEBHOOK_URL:  # New input for Slack Webhook URL
    description: "Slack Webhook URL for notifications."
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
