name: "Auto PR Alerts"

on:
  push:
    branches:
      - main

jobs:
  create-pr-alert:
    runs-on: ubuntu-latest
    steps:
      - name: Use Create Pull Request Alert Action
        uses: ./action.yaml
        with:
          repository: "username/repo"
          base-branch: "main"
          head-branch: "feature-branch"
          pr-title: "Automated Pull Request"
          pr-body: "This is an automated pull request for merging feature changes."
          github-token: ${{ secrets.GITHUB_TOKEN }}
