name: Notify Pull Request Slack

on:
  pull_request:
    types:
      - opened
      - reopened
      - closed
  issue_comment:
    types:
      - created
      - edited
  pull_request_review:
    types:
      - submitted
      - edited
      - dismissed

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check node version
        run: node --version

      - name: Check yarn version
        run: yarn --version

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn build

      - uses: ./
        with:
          slack-bot-token: "xoxb-2969427103-5744424979856-hSZyjtPH0ubNUg5qjHnUSsK2"
          slack-channel-id: "C05MB4KHBGU"
          user-mapping: |
            {
              "daint2git": "U031WCF7G5T"
            }
